defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: asnote-development

test:
  <<: *defaults
  database: asnote-test

production:
  <<: *defaults
  database: asnote-production

